services:
  collector:
    image: otel/opentelemetry-collector:latest
    volumes:
      - ./collector-config.yaml:/etc/otel-collector-config.yaml:ro
    command: ["--config", "/etc/otel-collector-config.yaml"]
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
      - "8889:8889" # Prometheus metrics

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: demo
    ports:
      - "5432:5432"

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    environment:
      - OTEL_SERVICE_NAME=gateway
      - OTEL_COLLECTOR_URL=http://collector:4318
      - PROCESSOR_1_URL=http://processor-1:8001/process
      - PROCESSOR_2_URL=http://processor-2:8001/process
    depends_on:
      - collector
      - processor-1
      - processor-2
    ports:
      - "8000:8000"

  processor-1:
    build:
      context: .
      dockerfile: processor/Dockerfile
    environment:
      - OTEL_SERVICE_NAME=processor-1
      - OTEL_COLLECTOR_URL=http://collector:4318
      - DATABASE_URL=postgresql://user:password@db:5432/demo
    depends_on:
      - collector
      - db
    ports:
      - "8001:8001"

  processor-2:
    build:
      context: .
      dockerfile: processor/Dockerfile
    environment:
      - OTEL_SERVICE_NAME=processor-2
      - OTEL_COLLECTOR_URL=http://collector:4318
      - DATABASE_URL=postgresql://user:password@db:5432/demo
    depends_on:
      - collector
      - db
    ports:
      - "8002:8001"

  zipkin:
    image: openzipkin/zipkin:2.23
    ports:
      - "9411:9411" # Zipkin UI & HTTP intake

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards

volumes:
  grafana-storage:
