version: "3.8"
services:
  app1:
    build:
      context: ./app
    environment:
      - INSTANCE=app1
      - SERVER=uvicorn
    networks:
      - web
  app2:
    build:
      context: ./app
    environment:
      - INSTANCE=app2
      - SERVER=uvicorn
    networks:
      - web
  app3:
    build:
      context: ./app
    environment:
      - INSTANCE=app3
      - SERVER=uvicorn
    networks:
      - web

  # Kong gateway
  kong:
    image: kong:3.6
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
    volumes:
      - ./kong-lc.yml:/usr/local/kong/declarative/kong.yml # Using least-connections load balancing
    ports:
      - "8000:8000" # proxy listen here
      - "8001:8001"
    depends_on:
      - app1
      - app2
      - app3
    networks:
      - web
      - web-db

networks:
  web:
    driver: bridge
  web-db:
    driver: bridge
