# docker-compose.yml
version: "3.9"
services:
  cassandra:
    image: cassandra:4
    environment:
      CASSANDRA_START_RPC: "true"
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra

volumes:
  cassandra_data:
