# docker-compose.yml
version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: iot
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: iot
    ports:
      - "5433:5432"
    volumes:
      - tsdb_data:/var/lib/postgresql/data

  cassandra:
    image: cassandra:4
    environment:
      CASSANDRA_START_RPC: "true"
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "9000:9000"
      - "8123:8123"
    environment:
      CLICKHOUSE_USER: myuser
      CLICKHOUSE_PASSWORD: mypass
      CLICKHOUSE_DB: default
    volumes:
      - clickhouse_data:/var/lib/clickhouse

volumes:
  pg_data:
  mongo_data:
  tsdb_data:
  cassandra_data:
  clickhouse_data:
