version: "3.8"

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--configFile=/etc/traefik/traefik.yml"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "./traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./traefik/acme.json:/acme.json"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - web

  app:
    build: ./app
    deploy:
      replicas: 5
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`localhost`)"
      - "traefik.http.routers.app.entrypoints=web"
      - "traefik.http.services.app.loadBalancer.server.port=80"
      - "traefik.http.services.app.loadBalancer.healthCheck.path=/health"
      - "traefik.http.services.app.loadBalancer.healthCheck.interval=10s"
      - "traefik.http.services.app.loadBalancer.sticky.cookie=true" # Enable sticky sessions.
      - "traefik.http.services.app.loadBalancer.sticky.cookie.name=app_session" # Name of the sticky session cookie.
      - "traefik.http.middlewares.ratelimiter.ratelimit.average=5" # Rate limit to 5 requests per second.
      - "traefik.http.middlewares.ratelimiter.ratelimit.burst=10" # Allow bursts of up to 10 requests.
    networks:
      - web

networks:
  web:
    driver: bridge
