# docker-compose.yml
version: "3.9"
services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "9000:9000"
      - "8123:8123"
    environment:
      CLICKHOUSE_USER: myuser
      CLICKHOUSE_PASSWORD: mypass
      CLICKHOUSE_DB: default
    volumes:
      - clickhouse_data:/var/lib/clickhouse

volumes:
  clickhouse_data:
