version: "3.8"

services:
  # REPLICATION SETUP (Primary + Replica)
  pg-primary:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: demo
    volumes:
      - pg-primary-data:/var/lib/postgresql/data # Use persistent volume
      - ./replication/primary/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./replication/primary/append-hba.sh:/docker-entrypoint-initdb.d/append-hba.sh
    ports:
      - "5432:5432"
    networks:
      - db-network

  pg-replica:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - ./replication/replica/init.sh:/docker-entrypoint-initdb.d/init.sh
    depends_on:
      - pg-primary
    networks:
      - db-network
    command: >
      bash -c '
      if [ ! -f /var/lib/postgresql/data/postgresql.conf ]; then
        until pg_isready -h pg-primary; do sleep 2; done;
        export PGPASSWORD=rep_pass;
        pg_basebackup -h pg-primary -U replicator -D /var/lib/postgresql/data -P -R -X stream;
      fi;
      exec docker-entrypoint.sh postgres'
